# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d724748264300a19f42575b5ee9e538833055ddd086045bbb3365f9647f87c582df0a1f9a610e0d94d946a1107eba3fc6eed6e90bd103b72fca363d8a3f213d

test:
  secret_key_base: 6db8a4646ee6110f3e01d7d66fa32d46f4c2ca13d4a3e4d9f3cfa2e1fb2f66fdb177215411e3cf5f50b8feb8f0e5c3d6a1a61826cd58143a6b38aa57f1636057

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
